runtime: custom
service: obiee-looker-240823
env: flex
automatic_scaling:

  min_num_instances: 1

  max_num_instances: 1
network:
  instance_tag: default-vpc-1
  name: default-vpc-1
  subnetwork_name: default-vpc-1


# runtime: custom
# service: obiee-looker
# env: flex
# network:
#   instance_tag: default-vpc-1
#   name: default-vpc-1
#   subnetwork_name: default-vpc-1